import Head from "next/head";
import CSR_Post from "../../components/CSR_Post";
import { usePaginatePosts } from "../../components/useRequest";

export default function Home() {
  const { posts, error, isLoadingMore, size, setSize, isReachingEnd } =
    usePaginatePosts();

  if (error) return <h1>Something went wrong!</h1>;
  if (!posts) return <h1>Loading..</h1>;

  return (
    <div>
      <Head>
        <title>Next SWR App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          maxWidth: "36rem",
          margin: "0 auto",
        }}
      >
        <h1
          style={{
            fontWeight: "bold",
            margin: "1.25rem",
          }}
        >
          My Posts
        </h1>

        {posts.map((post) => (
          <CSR_Post post={post} key={post.id} />
        ))}

        <button
          disabled={isLoadingMore || isReachingEnd}
          onClick={() => setSize(size + 1)}
        >
          {isLoadingMore
            ? "Loading..."
            : isReachingEnd
            ? "No more posts"
            : "Load more"}
        </button>
      </main>
    </div>
  );
}
