import { CSR_Post_STRINGS } from "@/constants/strings";
import Head from "next/head";
import CSR_Post from "../../components/CSR_Post";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Next SWR App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          maxWidth: "36rem",
          margin: "0 auto",
        }}
      >
        <h1
          style={{
            fontWeight: "bold",
            margin: "1.25rem",
          }}
        >
          {CSR_Post_STRINGS.myPost}
        </h1>

        {data.map((post) => (
          <CSR_Post post={post} key={post.id} />
        ))}
      </main>
    </div>
  );
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
